#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 26 10:37:55 2020

@author: louislin
"""
import pandas as pd
import tkinter as tk

reference= '/Users/louislin/Documents/Academic/References/Codes and Standards/Steel/aisc-shapes-database-v15.0.xlsx'
sheet = 'Database v15.0'
df = pd.read_excel(reference,sheet)

# Defines attributes and names
attributes = {"Area":"A",
        "Depth":"d",
        "Flange Width":"bf",
        "Flange Thickness":"tf",
        "Web Thickness":"tw",
        "Moment of Inertia X":"Ix",
        "Radius of Gyration X":"rx",
        "Moment of Inertia Y":"Iy",
        "Radius of Gyration Y":"ry",
        "Vertical Centroid":"y"
        }

def requestinfo(*arg):
    text_output.delete("0.0",tk.END)
    info = df.loc[df['AISC_Manual_Label'] == shape.get().upper()]
    if not info.empty:
        for i, (name,att) in enumerate(attributes.items()):
            text_output.insert(tk.END,f"{name:20}\t{att:2}\t{info[att].iloc[0]}\n")    
    else:
        return

# Create Frame
main = tk.Tk()

# Declare Variables
shape = tk.StringVar() 
shape.trace('w',requestinfo)

# Creats Widget
tk.Entry(main,textvariable = shape).grid(column = 0, row = 0,sticky="NW")
text_output = tk.Text(main,relief= tk.SUNKEN,width=40,height = 10,borderwidth =2 )
text_output.grid(column = 0 , row=1,sticky="NEWS")

main.mainloop()