#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 26 10:37:55 2020

@author: louislin
"""
import pandas as pd
import tkinter as tk

reference= './aisc-shapes-database-v15.0.xlsx'
sheet = 'Database v15.0'
df = pd.read_excel(reference,sheet)

''' This dictionary defines attributes and names that you want to display.
If you want more entries, the value of the dictionary entry should reflect
the correct column label in the excel sheet.
'''
attributes = {"Area":"A",
        "Depth":"d",
        "Flange Width":"bf",
        "Flange Thickness":"tf",
        "Web Thickness":"tw",
        "Moment of Inertia X":"Ix",
        "Radius of Gyration X":"rx",
        "Moment of Inertia Y":"Iy",
        "Radius of Gyration Y":"ry",
        "Vertical Centroid":"y"
        }

# Request information function
def requestinfo(*arg):
    text_output.delete("0.0",tk.END) # Clears the output refresh
    info = df.loc[df['AISC_Manual_Label'] == shape.get().upper()] # Matches the shape in the column Label Column and grabs the row
    if not info.empty: 
        for i, (name,att) in enumerate(attributes.items()):
            text_output.insert(tk.END,f"{name:20}\t{att:2}\t{info[att].iloc[0]}\n") # \t Allow for copy an paste into excel
    else:
        return

# Create tkinter Frame
main = tk.Tk()

# Declare Variables
shape = tk.StringVar() # Entry variable
shape.trace('w',requestinfo) # Runs the requestinfo function as you type

# Creats Widget
tk.Entry(main,textvariable = shape).grid(column = 0, row = 0,sticky="NW") # Entry widget
text_output = tk.Text(main,relief= tk.SUNKEN,width=40,height = 10,borderwidth =2 ) # Output text box
text_output.grid(column = 0 , row=1,sticky="NEWS") # Grid the output

main.mainloop() # Run the loop
